/******************************************************************************
* FILE: mpi_matrixSeq.c
* DESCRIPTION:
*   Calculates the matrix sequential. 
* AUTHOR: Evan Su
* LAST REVISED: 04/5/17
******************************************************************************/
//libraries
#include "mpi.h"
#include <sys/time.h>
#include <stdio.h>
#include <stdlib.h>

//define constants
#define  MASTER        0
#define  SLAVE      1
#define  TAG        0
#define  SECTOMICRO 1000000
#define  PRINT      0
#define     PRINTMATRIX    1
#define  RANGE        100


//function declarations
void masterCode(int, char*, char*);
void slaveCode(int,int);

void matrixMultipleSquare(int **, int**, int**, int);

void printMatrix(int **, int );

int ** makeMatrix(int);
void freeMatrix(int**, int);

void fillMatrix(int**, int**, int);
void readMatrix(int**, int**, int, FILE *, FILE *);

//Main function
/*
 *  Function name: main
 *  
 *  Brief: Main driver for the program
 *  
 *  Detail: The main driver initializes parallel processes.
 *          The master calls the master function
 *          The slave calls the slave function
 *          Both functions will run until computations are over.
 *
 *  Note: The slave functions does nothing, it is a placeholder
 *        for parallel code. 
 *          
 */
int main (int argc, char *argv[])
{
    //argc checker
    if(argc < 2)
    {
        //there are not enough arugments
        //note: this will not check if the arguements are in the correct positions
        printf("not enough arguments\n");
        printf("proper usage:\n srun mpi_BucketSeq <filename> <mpi arguements>");
        return 0;
    }
    
    //preprocessing
    int numtasks, taskid, len;
    char hostname[MPI_MAX_PROCESSOR_NAME];

    //parallel start
    MPI_Init(&argc, &argv);
    MPI_Comm_size(MPI_COMM_WORLD, &numtasks);
    MPI_Comm_rank(MPI_COMM_WORLD,&taskid);
    MPI_Get_processor_name(hostname, &len);


    if (taskid == MASTER)
    {
        //master code
        masterCode(atoi(argv[1]), argv[2], argv[3]);
    }
    else
    {
        //slave code
        //this code does nothing, placeholder for parallel.
        slaveCode(atoi(argv[1]), taskid);
    }

    MPI_Finalize();
    return 0;



}

/*
 *  Function name: masterCode
 *  
 *  Brief: matrix multiplication for the master node
 *  
 *  Detail: Makes matrixs based on size entered 
 *          If the size is greater than zero, the matrix
 *          are generated by the program
 *          else read from file 
 *          
 *          matrix multiple the two files
 *          
 *          prints the results
 */
void masterCode(int size, char * fileA, char * fileB)
{
    struct timeval startTime, endTime, diffTime;
    float elapsedTime = 0;
    int **matrixA, **matrixB, **matrixC;
    int scanResult;
    //int indexIn, indexOut;
    FILE * finA, * finB;
    srand(0);

    //fill matrix
    if(size > 0)
    {
        //make matrix
        matrixA = makeMatrix(size);
        matrixB = makeMatrix(size);
        matrixC = makeMatrix(size);
        //fill matrix
        fillMatrix(matrixA, matrixB, size);
    }
    else
    {
        //open files
        finA = fopen(fileA,"r");
        finB = fopen(fileB,"r");

        //scans the size
        scanResult = fscanf(finA, "%d", &size);
        scanResult = fscanf(finB, "%d", &size);        
        if(scanResult == 0)
        {
            //issues with the scan
            printf("read error\n");
            fclose(finA);
            fclose(finB);
            //exits
            return 0;
        }

        //make matrix
        matrixA = makeMatrix(size);
        matrixB = makeMatrix(size);
        matrixC = makeMatrix(size);

        //fill matrix from file
        readMatrix(matrixA, matrixB, size, finA, finB);
        
        //close files
        fclose(finA);
        fclose(finB);
    }

    //start time
    gettimeofday(&startTime, NULL);

    //matrix multiplication
    matrixMultipleSquare(matrixA, matrixB, matrixC, size);

    //stop time
    gettimeofday(&endTime, NULL);

     //calc diff time
    timersub(&endTime, &startTime, &diffTime);
    //converts time struct to float
    elapsedTime = (diffTime.tv_sec * SECTOMICRO + diffTime.tv_usec); 
    //prints result in microseconds
    printf("%f,",elapsedTime );

    //print matrixs
    if(PRINTMATRIX)
    {
        //new line the results
        printf("\n");

        //matrix A
        printf("matrix A:\n");
        printMatrix(matrixA, size);

        //matrix B
        printf("matrix B:\n");
        printMatrix(matrixB, size);

        //matrix C
        printf("matrix C:\n");
        printMatrix(matrixC, size);
    }

    //free memory
    freeMatrix(matrixA, size);
    matrixA = NULL;

    freeMatrix(matrixB, size);
    matrixB = NULL;

    freeMatrix(matrixC, size);
    matrixC = NULL;
}

/*
 *  Function name: slaveCode
 *  
 *  Brief: bucketsort code for the slave node
 *  
 *  Detail: The slave node does nothing in sequential calculations
 *  
 */
void slaveCode(int buckets, int rank)
{
    //printf("hello from slave");
}

/*
 *  Function name: matrixMultipleSquare
 *  
 *  Brief: matrix multiplication two matrixes and stores into the results
 *  
 *  Detail: matrix multiples matrixA and matrixB. Stores result in matrixResults
 *          by adding the values to the matrixResults.
 */
void matrixMultipleSquare(int **matrixA, int**matrixB, int**matrixResult, int length)
{
    int indexIn, indexOut, indexSub;
    for(indexOut = 0; indexOut < length; indexOut++)
    {
        for(indexIn = 0; indexIn < length; indexIn++)
        {
            for(indexSub = 0; indexSub < length; indexSub++)
            {
                //adds the results to the matrixresult
                matrixResult[indexOut][indexIn] += 
                        matrixA[indexOut][indexSub]*matrixB[indexSub][indexIn];
            }
        }
    }
}

/*
 *  Function name: printMatrix
 *  
 *  Brief: prints the matrix
 *  
 *  Detail: prints matrix using a for loop
 */
void printMatrix(int **matrix, int length)
{
    int indexIn, indexOut;
    for(indexOut = 0; indexOut < length; indexOut++)
    {
        for(indexIn = 0; indexIn < length; indexIn++)
        {
            printf("%8d", matrix[indexOut][indexIn]);
        }
        printf("\n");
    }
}

/*
 *  Function name: makeMatrix
 *  
 *  Brief: make Matrix
 *  
 *  Detail: makes the matrix of size*size using calloc and malloc
 */
int ** makeMatrix(int size)
{
    int index;
    int **tempPtr;

    tempPtr = (int **)malloc(sizeof(int*) * size);    
    for (index = 0; index < size; index ++)
    {
        tempPtr[index] = (int*)calloc(size ,sizeof(int));
    }
    return tempPtr;
}

/*
 *  Function name: freeMatrix
 *  
 *  Brief: makeMatrix
 *  
 *  Detail: frees the matrix memory
 */
void freeMatrix(int ** matrix, int size)
{
    int index;
    for(index = 0; index < size; index++)
    {
        free(matrix[index]);
    }
    free(matrix);
}

/*
 *  Function name: fillMatrix
 *  
 *  Brief: fills matrixA and B with numbers
 *  
 *  Detail: fills matrixA and matrixB with rand()
 *
 *  Notes:  srand must be seeded before the function call
 */
void fillMatrix(int** matrixA, int **matrixB, int size)
{
    int indexOut, indexIn;

    for(indexOut = 0; indexOut < size; indexOut++)
    {
        for(indexIn = 0; indexIn < size; indexIn++)
        {
            //fills matrix of A and B at [indexOut][indexIn] with rand numbers
            matrixA[indexOut][indexIn] = rand() %RANGE;
            matrixB[indexOut][indexIn] = rand() %RANGE;
        }
    }
}

/*
 *  Function name: readMatrix
 *  
 *  Brief: fills matrixA and matrixB from files
 *  
 *  Detail: matrixA is filled with numbers from finA 
 *          matrixB is filled with numberes from finB
 *
 *  Notes:  finA and finB must point to a file before using this function
 */
void readMatrix(int** matrixA, int** matrixB, int size, FILE * finA, FILE * finB)
{
    int indexIn, indexOut;
    int scanResult;
    
    for(indexOut = 0; indexOut < size; indexOut ++)
    {
        for(indexIn = 0; indexIn < size; indexIn++)
        {
            //reads the numbers into matrixA and matrixB
            scanResult = fscanf(finA, "%d", &matrixA[indexOut][indexIn]);
            scanResult = fscanf(finB, "%d", &matrixB[indexOut][indexIn]);
            if(scanResult == 0)
            {
                //read error
                printf("read error\n");
            }
        }
    }

}
